remote_theme: daviddarnes/alembic
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Bayesci İstatistiğe Giriş - Murat Koptur
description: Bayesci istatistiğe giriş
social:
  name: Murat Koptur
  links:
    - https://www.facebook.com/muratkoptur
    - https://www.linkedin.com/in/muratkoptur
    - https://github.com/mrtkp9993
webmaster_verifications:
  google: _58A-s2Bb2HRB74P5Hac84hQtEUWMQEjI37P6lnAYp8
google_analytics: UA-138447594-4
titles_from_headings:
  strip_title: true
navigation_footer:
  Murat Koptur: https://muratkoptur.com
  LinkedIn: https://www.linkedin.com/in/muratkoptur
  Facebook: https://www.facebook.com/muratkoptur
